from utils import *

camera = Camera()
motor = Motor()
dispenser = Dispenser()
plataforma = Plataforma()
sleep(1)

motor.home()
sleep(1)
dispenser.drop()
sleep(2)
camera.Flash()
sleep(1)
camera.Flash(False)
motor.move(67)
sleep(0.5)
plataforma.eject()

sleep(1)
dispenser.drop()
sleep(2)
camera.Flash()
sleep(1)
camera.Flash(False)
motor.move(0)
sleep(0.5)
plataforma.eject()

sleep(1)
dispenser.drop()
sleep(2)
camera.Flash()
sleep(1)
camera.Flash(False)
motor.move(67)
sleep(0.5)
plataforma.eject()